version: "3.5"

services:
  db:
   container_name: db
   image: postgres:latest
   environment:
     - POSTGRES_PASSWORD=123
     - POSTGRES_USER=postgres
     - POSTGRES_DB=attus-api
   ports:
     - "5432:5432"
   volumes:
     - ./init.sql:/docker-entrypoint-initdb.d/init.sql
   networks:
     - attus-network

  api01:
   build: .
   depends_on:
     - db
   ports:
     - "8080:8080"
   networks:
     - attus-network

networks:
  attus-network:
    driver: bridge